---
- name: Install ISC DHCP server
  apt:
    name: isc-dhcp-server
    update_cache: yes

- name: Install DHCPDump
  apt:
    name: dhcpdump
    update_cache: yes

- name: Creates first config
  copy:
    src: files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

- name: Creates second config
  copy:
    src: files/isc-dhcp-server
    dest: /etc/default/isc-dhcp-server

- name: Restart isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: restarted