---
- name: Install TFTP-client
  apt:
    name: tftp
    update_cache: yes

- name: Install TFTP-server
  apt:
    name: tftpd-hpa
    update_cache: yes

- name: chown directories
  file:
    path: /srv/tftp
    state: directory
    owner: tftp
    group: tftp



- name: Creates config one more
  file:
    src: templates/tftpd_hpa
    dest: /etc/default/tftpd_hpa

- name: Reload service tftpd-hpa
  service:
    name: tftpd-hpa
    state: restarted