---
- name: Install PXELinux
  apt:
    name: pxelinux
    update_cache: yes

- name: Creates dirs
  shell:
    cmd: |
      cd /srv/tftp
      sudo mkdir pxelinux
      cd pxelinux
      sudo mkdir pxelinux.cfg

- name: Creates config
  template:
    src: templates/default
    dest: /srv/tftp/pxelinux/default