---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    update_cache: yes

- name: Copy conf for dnsmasq
  copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Download
  get_url:
    url: https://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso
    dest: /tmp/ubuntu-20.04.2-live-server-amd64.iso

- name: Shell commands
  shell:
    cmd: mount -v ubuntu-20.04.2.0-desktop-amd64.iso /mnt/

- name: Copy mnt
  copy:
    src: /mnt/install/netboot/*
    dst: /srv/tftp/
    remote_src: yes

- name: Apache installation
  apt:
    name: apache2
    update_cache: yes

- name: One more shell commands
  shell:
    cmd: |
      systemctl start apache2
      systemctl enable apache2

- name: Copy mnt 2
  copy:
    src: /mnt/*
    dst: /var/www/html/
    remote_src: yes

- name: Creates directories
  file:
    path: /var/www/html/ubuntu
    state: directory

- name: Creates directories
  file:
    path: /var/www/html/ubuntu/preseed
    state: directory



- name: Creation of the first PXE config file
  copy:
    src: files/local-sources.seed
    dest: /var/www/html/ubuntu/preseed/local-sources.seed

- name: Creates directories
  file:
    path: /srv/tftp/ubuntu-installer
    state: directory

- name: Creates directories
  file:
    path: /srv/tftp/ubuntu-installer/amd64
    state: directory

- name: Creates directories
  file:
    path: /srv/tftp/ubuntu-installer/amd64/boot-screens
    state: directory


- name: Creation of the second PXE config file
  copy:
    src: files/txt
    dest: /srv/tftp/ubuntu-installer/amd64/boot-screens/txt.cfg

- name: Creation of the third PXE config file
  copy:
    src: files/rqtxt
    dest: /srv/tftp/ubuntu-installer/amd64/boot-screens/rqtxt.cfg

- name: Creation of the fourthPXE config file
  copy:
    src: files/txt
    dest: /srv/tftp/ubuntu-installer/amd64/boot-screens/menu.cfg
